name: EKS Upgrade

on:
  workflow_dispatch:

  schedule:
     - cron: '0 2 1 * *'

jobs:
  upgrade:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd
        working-directory: .

      - name: List repository files
        run: |
          pwd
          ls -la
          find . -maxdepth 3
        working-directory: .

##################################################
#  Validate Github Secrets
##################################################

      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "ACCESS KEY is EMPTY"
          else
            echo "ACCESS KEY exists"
          fi

          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "SECRET KEY is EMPTY"
          else
            echo "SECRET KEY exists"
          fi

###############################
# Configure AWS
###############################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#########################
# check EKS Version
#########################

      - name: Check EKS Version
        run: |
           chmod +x scripts/check-eks-version.sh
           ./scripts/check-eks-version.sh
        working-directory: .

##########################
# Terraform
##########################
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        if: env.UPGRADE_REQUIRED == 'true'
        run: terraform init

      - name: Terraform Validate
        if: env.UPGRADE_REQUIRED == 'true'
        run: terraform validate

      - name: Terraform Plan
        if: env.UPGRADE_REQUIRED == 'true'
        run: terraform plan

      - name: Terraform Apply
        if: env.UPGRADE_REQUIRED == 'true'
        run: terraform apply -auto-approve

######################
# Kubernetes Tools
######################

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

#######################
# Configure Kubeconfig
#######################

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name eks-upgrade-prod

##################################################
# Automated Validation Suite 
##################################################

      - name: Run Cluster Validation Suite
        if: env.UPGRADE_REQUIRED == 'true'
        run: |
          chmod +x scripts/validate-cluster.sh
          ./scripts/validate-cluster.sh
        working-directory: .

################################################
# AWS Load Balancer Validation
##################################################

      - name: Verify Load Balancers
        run: |
          aws elbv2 describe-load-balancers

      - name: Verify Target Groups
        run: |
          aws elbv2 describe-target-groups

      - name: Verify Target Health
        run: |
          TARGET_GROUP_ARN=$(aws elbv2 describe-target-groups \
            --query "TargetGroups[0].TargetGroupArn" \
            --output text)

          if [ "$TARGET_GROUP_ARN" != "None" ]; then
            aws elbv2 describe-target-health \
              --target-group-arn "$TARGET_GROUP_ARN"
          else
            echo "No Target Groups Found"
          fi

      - name: No Upgrade Required
        if: env.UPGRADE_REQUIRED == 'false'
        run: |
          {
            echo "# ✅ Monthly EKS Check"
            echo ""
            echo "Cluster is already running the latest supported Kubernetes version."
            echo ""
            echo "No upgrade was required."
          } >> "$GITHUB_STEP_SUMMARY"

##################################################
# Workflow Summary
##################################################

      - name: Upgrade Summary
        if: success() && env.UPGRADE_REQUIRED == 'true'
        run: |
          {
            echo "## EKS Upgrade Verification Successful"
            echo ""
            echo "| Check | Status |"
            echo "|------|--------|"
            echo "| Terraform Apply | ✅ |"
            echo "| Control Plane | ✅ |"
            echo "| Node Group | ✅ |"
            echo "| Worker Nodes | ✅ |"
            echo "| Pods | ✅ |"
            echo "| Deployments | ✅ |"
            echo "| Services | ✅ |"
            echo "| Cluster Autoscaler | ✅ |"
            echo "| AWS Load Balancer Controller | ✅ |"
            echo "| ArgoCD | ✅ |"
            echo "| Load Balancer | ✅ |"
            echo "| Target Groups | ✅ |"
          } >> $GITHUB_STEP_SUMMARY
